def sum(n):
    return n*(n+_1)/2
#space complexity:0(1),Auxlilary space=0(1) Linear space
def arraysum(a):
    sum=0
    for i in a:
        sum = sum +1

        return(sum)
    a = [12,3,4,15]
    arraysum(a)
# with the size of the array ,the space also required increases
#pace complexity:0(n), Auiliary space=0(1)
def summ(n):
    if(n<=0):
        return
    return n+ summ(n-1)
sum(12345)
arraysum(123)
summ(1234)